spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/order-service?useSSL=false"
    username: root
    password: root

  liquibase:
    change-log: classpath:db/changelog/db-changelog.yml
  jpa:
    hibernate:
      ddl-auto:  none
    show-sql: true